#!/bin/sh -e
# Fakeroot and lein don't get along, so we set ownership after the fact.
chown -R root:root /usr/lib/disthene-reader
chown root:root /usr/bin/disthene-reader
chown disthene:disthene /var/log/disthene-reader
chown -R disthene:disthene /etc/disthene-reader
chown root:root /etc/init.d/disthene-reader

if [ -x "/etc/init.d/disthene-reader" ]; then
	update-rc.d disthene-reader start 50 2 3 4 5 . stop 50 0 1 6 . >/dev/null
	invoke-rc.d disthene-reader start || exit $?
fi
