#!/bin/sh -e
# Fakeroot and lein don't get along, so we set ownership after the fact.
chown -R root:root /usr/lib/disthene-reader
chown disthene-reader:disthene-reader /var/log/disthene-reader
chown -R disthene-reader:disthene-reader /etc/disthene-reader
